services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super-pizza-shop
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    depends_on:
      - db
    environment:
       - DATABASE_URL=postgresql://postgres:postgres@db:5432/super-pizza-shop?schema=public
       - PORT=${PORT}
       - SALT_POUNDS=${SALT_POUNDS}
       - ADMIN_NAME=${ADMIN_NAME}
       - ADMIN_EMAIL=${ADMIN_EMAIL}
       - ADMIN_PASSWORD=${ADMIN_PASSWORD}
       - SECRET=${SECRET}
       - EXPIRES_IN_SECODS=${EXPIRES_IN_SECODS}
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run dev
      "
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  postgresdata:

networks:
  app-network:
    driver: bridge
